# Security Pipeline (This is with the Checkov)
name: Security Pipeline (With Checkov)

on:
  push:
    branches:
      - checkov
  pull_request:
    branches:
      - checkov

jobs:
  security-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: false
          quiet: true
